### ISSUE TITLE
libopencv_core.so.3.4   No such file or directory

### ISSUE THREAD

**Issue by melodybinbin** [Markbess/boteye_ros#2]
Hello, I run into an issue as following:

vio@vio:~/boteye_ros/build$ rosrun boteye_ros ros_node 
/home/vio/boteye_ros/src/ros_node: error while loading shared libraries: libopencv_core.so.3.4: cannot open shared object file: No such file or directory
vio@vio:~/boteye_ros/build$

Then I have checked the CMakeLists.txt, and don't find the information of opencv3.4.
What's wrong with this? Thank you advance!
你好，报上面的错误是怎么回事呢？期待您的回复，谢谢！

**Comment by TAO270** [comment]
@melodybinbin 
看你的问题是编译已经通过了,执行的时候没有找到opencv3.4.
整个工程是基于OpenCV 3.0 以上的，先确定一下你已经装了OpenCV 3.0以上版本
使用命令 pkg-config --modversion opencv
另外，这个工程使用了 ROS 的cv_bridge 包，indigo版本是基于OpenCV2.4构建的，所以需要手动安装opencv3.0的cv_bridge.

**Comment by melodybinbin** [comment]
嗯嗯，我一开始是安装的OpenCV 3.1.0,使用命令：pkg-config --modversion opencv是3.1.0
使用命令： sudo find / -name "libopencv_core.so.3.1*"
vio@vio:~/boteye_ros/build$ sudo find / -name "libopencv_core.so.3.1*"
/usr/lib/x86_64-linux-gnu/libopencv_core.so.3.1.0
/usr/lib/x86_64-linux-gnu/libopencv_core.so.3.1
find: ‘/run/user/1000/gvfs’: Permission denied
vio@vio:~/boteye_ros/build$
而找不到libopencv_core.so.3.4，然后我源码编译安装OpenCV 3.4.0后，可以找到libopencv_core.so.3.4了。再运行rosrun boteye_ros ros_node，还是有错误，无法运行。
最后我将boteye_ros直接拷贝到我的catkin_ws中的src目录下：
然后再catkin_ws路径下catkin_make，就可以正常运行了。

想问下：是不是ROS功能包不能像下面这样编译呢？
···
cd boteye_ros
mkdir build
cd build
cmake ..
make
··· 
ROS功能包是不是要放在工作空间的src文件夹中，然后执行命令catkin_make进行编译？

**Comment by TAO270** [comment]
@melodybinbin 
是可以用cmake编译的，找不到node节点复制到src下就行
https://github.com/Markbess/boteye_ros/blob/master/CMakeLists.txt#L96
https://github.com/Markbess/boteye_ros/blob/master/CMakeLists.txt#L103

**Comment by melodybinbin** [comment]
好的，谢谢。
