### ISSUE TITLE
提取摄像头的时间戳

### ISSUE THREAD

**Issue by melodybinbin** [Markbess/boteye_ros#3]
你好，如果不添加camera_info的topic到源程序，使用您提供的ros::time怎么得到时间戳呢？期待您的回复，谢谢！

**Comment by TAO270** [comment]
@melodybinbin 
相机回来的时间是一个基于内部时钟的计数，单位是100us，只需要用第一次采集时刻的ros时间一直叠加这个计数就能得到相对ros::time的时间。函数hardTimeToSoftTime实现了这个功能。
https://github.com/Markbess/boteye_ros/blob/master/src/ros_node.cpp#L90
当然，就像 [#1](https://github.com/Markbess/boteye_ros/issues/1) 提到的那样，内部时间和真实时间会有个偏差。但是图像之间和imu之间的时间差是准确的。

**Comment by melodybinbin** [comment]
哦哦，我在ros_node.cpp中添加了
pub_time_stamp.publish(img_header);//添加
pub_left.publish(msg_left);
pub_right.publish(msg_right);
……
ros::NodeHandle nh;
    image_transport::ImageTransport it(nh);
    image_transport::Publisher pub_left=it.advertise("/boteye/left/image_color_raw",50);

**Comment by melodybinbin** [comment]
@Markbess 
嗯嗯，好的，谢谢。
我在ros_node.cpp中做了一点修改如下（添加了两行）：
ros::NodeHandle nh;
ros::Publisher pub_time_stamp=nh.advertise<std_msgs::Header>("/boteye/time_stamp",50);//添加
image_transport::ImageTransport it(nh);
image_transport::Publisher pub_left=it.advertise("/boteye/left/image_color_raw",50);
……
sensor_msgs::ImagePtr msg_right=cv_bridge::CvImage(img_header, "bgr8", temp.r).toImageMsg();
pub_time_stamp.publish(img_header);//添加
pub_left.publish(msg_left);
pub_right.publish(msg_right);

然后自己写了一个订阅者程序listen.cpp：
……
ros::NodeHandle n;
ros::Subscriber sub1 = n.subscribe ("/boteye/time_stamp", 10, Callback_camera);
……
//回调函数
void Callback_camera(const std_msgs::Header msg_camera)
{
    ofstream fout;
    cout << "camera_frame_id: " << msg_camera.frame_id << endl;
    cout << "camera_stamp: " << msg_camera.stamp << " ";
    //fout.open("/home/vio/camera.txt");
    fout.open("/home/vio/camera.txt",ios::out|ios::app);
    fout << msg_camera.stamp << " ";
……

1.这样得到的就是左右目的时间戳吧？
2.在：ros::Publisher pub_time_stamp=nh.advertise<std_msgs::Header>("/boteye/time_stamp",50);//添加
和ros::Subscriber sub1 = n.subscribe ("/boteye/time_stamp", 10, Callback_camera);
中的50和10对时间戳有影响吗？

**Comment by TAO270** [comment]
@melodybinbin 
每一帧的image时间戳放在img_msg->header.stamp里，需要转化为秒的话直接使用
img_msg->header.stamp.toSec()
可以这样子做，你要保存时间戳到txt文件的话，直接在发布图像话题的时候保存就行。
https://github.com/Markbess/boteye_ros/blob/master/src/ros_node.cpp#L782
后面添加：
ofstream fout;
cout << "camera_frame_id: " << img_header.frame_id << endl;
cout << "camera_stamp: " << img_header.stamp << " ";
//fout.open("/home/vio/camera.txt");
fout.open("/home/vio/camera.txt",ios::out|ios::app);
fout << img_header.stamp << " ";
数字50和10表示缓存队列的大小，如果上一个数据还没有处理，就把当前数据缓存，缓存大小超过这个数就丢弃。

**Comment by melodybinbin** [comment]
@Markbess 
哦哦，好的，谢谢啦！
